# build_climate_cache_batch.py
#
# Batch climate-cache builder for SHIFT Atlas.
#
# Usage from repo data folder:
#     cd C:\Users\kobas\00_Repos\2605_ShiftAtlas_git\data
#     python build_climate_cache_batch.py
#
# Output:
#     climate_cache.json

import json
import re
import time
import requests
from datetime import datetime, timezone
from pathlib import Path

OUT_PATH = Path("climate_cache.json")
INDEX_PATH = Path("..") / "index.html"

START_DATE = "2019-01-01"
END_DATE = "2023-12-31"

BATCH_SIZE = 8
DELAY_SECONDS = 5.0
TIMEOUT = 90


def cache_key(lat, lon):
    return f"{float(lat):.3f},{float(lon):.3f}"


def extract_cases_from_index(index_path=INDEX_PATH):
    if not index_path.exists():
        raise FileNotFoundError(f"Could not find {index_path}")

    text = index_path.read_text(encoding="utf-8", errors="ignore")
    start = text.find("const cases")
    if start == -1:
        start = 0
    end = text.find("const CASE_TAX", start)
    if end == -1:
        end = min(len(text), start + 500000)
    region = text[start:end]

    patterns = [
        re.compile(
            r"id\s*:\s*(\d+).*?name\s*:\s*['\"]([^'\"]+)['\"].*?coords\s*:\s*\[\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*\]",
            re.S,
        ),
        re.compile(
            r'"id"\s*:\s*(\d+).*?"name"\s*:\s*"([^"]+)".*?"coords"\s*:\s*\[\s*(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)\s*\]',
            re.S,
        ),
    ]

    cases = []
    for pattern in patterns:
        for m in pattern.finditer(region):
            cases.append(
                {
                    "id": int(m.group(1)),
                    "name": m.group(2),
                    "lat": float(m.group(3)),
                    "lon": float(m.group(4)),
                }
            )
        if cases:
            break

    seen = set()
    unique = []
    for c in cases:
        k = cache_key(c["lat"], c["lon"])
        if k not in seen:
            seen.add(k)
            unique.append(c)

    return unique


def normalise_daily_response(response_json):
    if isinstance(response_json, list):
        return response_json
    if isinstance(response_json, dict):
        return [response_json]
    return []


def monthly_from_daily(daily):
    times = daily.get("time", [])
    TX = daily.get("temperature_2m_max", [])
    TN = daily.get("temperature_2m_min", [])
    PR = daily.get("precipitation_sum", [])

    tx_sum = [0.0] * 12
    tn_sum = [0.0] * 12
    pr_sum = [0.0] * 12
    dn = [0] * 12
    pn = [0] * 12

    for i, t in enumerate(times):
        m = int(t[5:7]) - 1

        tx = TX[i] if i < len(TX) and TX[i] is not None else None
        tn = TN[i] if i < len(TN) and TN[i] is not None else None
        pr = PR[i] if i < len(PR) and PR[i] is not None else None

        if tx is not None and tn is not None:
            tx_sum[m] += tx
            tn_sum[m] += tn
            dn[m] += 1
        if pr is not None:
            pr_sum[m] += pr
            pn[m] += 1

    yrs = len(set(t[:4] for t in times)) or 5

    return {
        "tmax": [round(tx_sum[i] / dn[i], 1) if dn[i] else None for i in range(12)],
        "tmin": [round(tn_sum[i] / dn[i], 1) if dn[i] else None for i in range(12)],
        "prec": [round(pr_sum[i] / yrs) if pn[i] else None for i in range(12)],
        "ah": [None] * 12,
        "sr": [None] * 12,
    }


def is_valid(d):
    return (
        isinstance(d, dict)
        and isinstance(d.get("tmax"), list)
        and len(d["tmax"]) == 12
        and isinstance(d.get("tmin"), list)
        and len(d["tmin"]) == 12
        and isinstance(d.get("prec"), list)
        and len(d["prec"]) == 12
        and any(v is not None for v in d["tmax"])
    )


def write_cache(locations):
    out = {
        "generated": datetime.now(timezone.utc).isoformat(),
        "baseline": "Open-Meteo historical archive, daily 2019-01-01 to 2023-12-31 aggregated to monthly summaries",
        "variables": ["tmax", "tmin", "prec"],
        "source_note": "Generated by build_climate_cache_batch.py. Essential variables only; humidity and solar radiation are omitted to avoid rate limits.",
        "locations": locations,
    }
    OUT_PATH.write_text(json.dumps(out, separators=(",", ":")), encoding="utf-8")
    print(f"  -> Saved {len(locations)} locations to {OUT_PATH}")


def fetch_batch(batch):
    latitudes = ",".join(f"{c['lat']:.3f}" for c in batch)
    longitudes = ",".join(f"{c['lon']:.3f}" for c in batch)

    vars_ = "temperature_2m_max,temperature_2m_min,precipitation_sum"
    url = (
        "https://archive-api.open-meteo.com/v1/archive"
        f"?latitude={latitudes}&longitude={longitudes}"
        f"&start_date={START_DATE}&end_date={END_DATE}"
        f"&daily={vars_}&timezone=GMT"
    )

    r = requests.get(url, timeout=TIMEOUT)

    if r.status_code == 429:
        raise RuntimeError("RATE_LIMITED")
    if r.status_code != 200:
        raise RuntimeError(f"HTTP {r.status_code}: {r.text[:300]}")

    return normalise_daily_response(r.json())


def main():
    cases = extract_cases_from_index()
    print(f"Found {len(cases)} unique case locations in ../index.html")

    existing = {}
    if OUT_PATH.exists():
        try:
            existing = json.loads(OUT_PATH.read_text(encoding="utf-8")).get("locations", {})
            print(f"Loaded {len(existing)} existing cached locations")
        except Exception as e:
            print(f"Could not read existing cache: {e}")

    locations = dict(existing)
    remaining = [c for c in cases if not is_valid(locations.get(cache_key(c["lat"], c["lon"])))]

    if not remaining:
        print("All case locations are already cached.")
        return

    print(f"Need to fetch {len(remaining)} missing case locations.")
    print("If this immediately says RATE LIMITED, wait 1-2 hours and rerun.\n")

    for start in range(0, len(remaining), BATCH_SIZE):
        batch = remaining[start : start + BATCH_SIZE]
        labels = ", ".join(c["name"] for c in batch[:3])
        if len(batch) > 3:
            labels += f" + {len(batch)-3} more"

        print(f"Batch {start//BATCH_SIZE + 1}: {labels} ... ", end="", flush=True)

        try:
            results = fetch_batch(batch)
        except RuntimeError as e:
            if str(e) == "RATE_LIMITED":
                print("RATE LIMITED - saved progress and stopped.")
                write_cache(locations)
                return
            print(f"FAILED: {e}")
            write_cache(locations)
            time.sleep(DELAY_SECONDS)
            continue

        ok = 0
        for c, result in zip(batch, results):
            d = monthly_from_daily(result.get("daily", {}))
            if is_valid(d):
                locations[cache_key(c["lat"], c["lon"])] = d
                ok += 1

        print(f"OK {ok}/{len(batch)}")
        write_cache(locations)
        time.sleep(DELAY_SECONDS)

    print("\nDone.")
    write_cache(locations)


if __name__ == "__main__":
    main()
